"""add_user_upload_tables

Revision ID: 2323bc3b4eba
Revises: 5e0294e5bf63
Create Date: 2026-03-27 16:57:06.059381

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2323bc3b4eba'
down_revision: Union[str, Sequence[str], None] = '5e0294e5bf63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_graph_edges',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('source_concept', sa.Text(), nullable=False),
    sa.Column('target_concept', sa.Text(), nullable=False),
    sa.Column('edge_type', sa.String(length=64), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_user_graph_edges_user_id', 'user_graph_edges', ['user_id'], unique=False)
    op.create_table('user_papers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('upload_path', sa.String(length=512), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('concept_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_user_papers_status', 'user_papers', ['status'], unique=False)
    op.create_index('ix_user_papers_user_id', 'user_papers', ['user_id'], unique=False)
    op.create_table('user_concepts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('concept', sa.Text(), nullable=False),
    sa.Column('paper_id', sa.UUID(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['paper_id'], ['user_papers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_user_concepts_paper_id', 'user_concepts', ['paper_id'], unique=False)
    op.create_index('ix_user_concepts_user_id', 'user_concepts', ['user_id'], unique=False)
    op.create_table('user_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('paper_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('celery_task_id', sa.String(length=255), nullable=True),
    sa.Column('error_msg', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['paper_id'], ['user_papers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_user_jobs_paper_id', 'user_jobs', ['paper_id'], unique=False)
    op.create_index('ix_user_jobs_status', 'user_jobs', ['status'], unique=False)
    op.create_index('ix_user_jobs_user_id', 'user_jobs', ['user_id'], unique=False)
    op.add_column('users', sa.Column('lifetime_uploads', sa.Integer(), server_default=sa.text('0'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'lifetime_uploads')
    op.drop_index('ix_user_jobs_user_id', table_name='user_jobs')
    op.drop_index('ix_user_jobs_status', table_name='user_jobs')
    op.drop_index('ix_user_jobs_paper_id', table_name='user_jobs')
    op.drop_table('user_jobs')
    op.drop_index('ix_user_concepts_user_id', table_name='user_concepts')
    op.drop_index('ix_user_concepts_paper_id', table_name='user_concepts')
    op.drop_table('user_concepts')
    op.drop_index('ix_user_papers_user_id', table_name='user_papers')
    op.drop_index('ix_user_papers_status', table_name='user_papers')
    op.drop_table('user_papers')
    op.drop_index('ix_user_graph_edges_user_id', table_name='user_graph_edges')
    op.drop_table('user_graph_edges')
    # ### end Alembic commands ###
