"""add trend_scores unique constraint

Revision ID: 2ce13f2f4f5f
Revises: ed201e98a3cd
Create Date: 2026-03-12 16:49:59.555499

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ce13f2f4f5f'
down_revision: Union[str, Sequence[str], None] = 'ed201e98a3cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_trend_scores_kw_cat_start', 'trend_scores', ['keyword', 'category', 'window_start'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_trend_scores_kw_cat_start', 'trend_scores', type_='unique')
    # ### end Alembic commands ###
