"""initial schema

Revision ID: 5b11530242f2
Revises: 
Create Date: 2026-03-12 16:22:10.536433

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5b11530242f2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('keyword_counts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('keyword', sa.String(length=256), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('window_date', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_keyword_counts_keyword_category', 'keyword_counts', ['keyword', 'category'], unique=False)
    op.create_index('ix_keyword_counts_window_date', 'keyword_counts', ['window_date'], unique=False)
    op.create_table('papers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('arxiv_id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('abstract', sa.Text(), nullable=False),
    sa.Column('authors', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('categories', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_papers_arxiv_id'), 'papers', ['arxiv_id'], unique=True)
    op.create_index('ix_papers_categories', 'papers', ['categories'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_papers_ingested_at'), 'papers', ['ingested_at'], unique=False)
    op.create_index(op.f('ix_papers_published_at'), 'papers', ['published_at'], unique=False)
    op.create_table('trend_scores',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('keyword', sa.String(length=256), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('trend_direction', sa.String(length=16), nullable=False),
    sa.Column('window_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('window_end', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_trend_scores_keyword_category', 'trend_scores', ['keyword', 'category'], unique=False)
    op.create_index(op.f('ix_trend_scores_window_start'), 'trend_scores', ['window_start'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trend_scores_window_start'), table_name='trend_scores')
    op.drop_index('ix_trend_scores_keyword_category', table_name='trend_scores')
    op.drop_table('trend_scores')
    op.drop_index(op.f('ix_papers_published_at'), table_name='papers')
    op.drop_index(op.f('ix_papers_ingested_at'), table_name='papers')
    op.drop_index('ix_papers_categories', table_name='papers', postgresql_using='gin')
    op.drop_index(op.f('ix_papers_arxiv_id'), table_name='papers')
    op.drop_table('papers')
    op.drop_index('ix_keyword_counts_window_date', table_name='keyword_counts')
    op.drop_index('ix_keyword_counts_keyword_category', table_name='keyword_counts')
    op.drop_table('keyword_counts')
    # ### end Alembic commands ###
