"""add keyword_counts unique constraint

Revision ID: ed201e98a3cd
Revises: 5b11530242f2
Create Date: 2026-03-12 16:40:18.978929

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed201e98a3cd'
down_revision: Union[str, Sequence[str], None] = '5b11530242f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_keyword_counts_kw_cat_date', 'keyword_counts', ['keyword', 'category', 'window_date'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_keyword_counts_kw_cat_date', 'keyword_counts', type_='unique')
    # ### end Alembic commands ###
